name: release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set version env variable
        run: |
          # 获取package.json中的版本号
          version=$(node -p "require('./package.json').version")
          echo "RELEASE_VERSION=${version}" >> $GITHUB_ENV
          # 输出版本号
          echo Release version: ${{ env.RELEASE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:production

      - name: upload files to OSS
        uses: Allaihub/aliyun-oss-website-action@master
        with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: yiruoai-open
          # use your own endpoint
          endpoint: oss-cn-beijing.aliyuncs.com
          folder: dist
          prefix: web/chatflow/tpl1
          skipSetting: true
          htmlCacheControl: no-cache
          imageCacheControl: max-age=864001
          otherCacheControl: max-age=2592001
          # 必须加这个，不然会干掉所有文件
          onlyUpload: true
